<?php
error_reporting(E_ALL & ~E_NOTICE);
@require_once("requires/session.php");
$objDb  		= new Database( );

mysql_query('TRUNCATE TABLE activity');
mysql_query('TRUNCATE TABLE activity_log');
mysql_query('TRUNCATE TABLE baseline');
mysql_query('TRUNCATE TABLE baseline_mapping_boqs');
mysql_query('TRUNCATE TABLE baseline_template');
mysql_query('TRUNCATE TABLE base_data_cube');
mysql_query('TRUNCATE TABLE boq');
mysql_query('TRUNCATE TABLE boqdata');
mysql_query('TRUNCATE TABLE ipc');
mysql_query('TRUNCATE TABLE ipcv');
mysql_query('TRUNCATE TABLE ipc_log');
mysql_query('TRUNCATE TABLE kpidata');
mysql_query('TRUNCATE TABLE kpidata_etl');
mysql_query('TRUNCATE TABLE kpidata_result');
mysql_query('TRUNCATE TABLE kpiscale');
mysql_query('TRUNCATE TABLE kpi_activity');
mysql_query('TRUNCATE TABLE kpi_base_level_report');
mysql_query('TRUNCATE TABLE kpi_monthly_progress_report');
mysql_query('TRUNCATE TABLE kpi_templates');
mysql_query('TRUNCATE TABLE kpi_top_level_report');
mysql_query('TRUNCATE TABLE kpi_total_baseline');
mysql_query('TRUNCATE TABLE locations');
mysql_query('TRUNCATE TABLE maindata');
mysql_query('TRUNCATE TABLE maindata_log');
mysql_query('TRUNCATE TABLE main_data_cube');
mysql_query('TRUNCATE TABLE mildata');
mysql_query('TRUNCATE TABLE pages_visit_log');
mysql_query('TRUNCATE TABLE planned');
mysql_query('TRUNCATE TABLE progress');
mysql_query('TRUNCATE TABLE progressmonth');
mysql_query('TRUNCATE TABLE progressmonth_log');
mysql_query('TRUNCATE TABLE project');
mysql_query('TRUNCATE TABLE project_currency');
mysql_query('TRUNCATE TABLE project_days');
mysql_query('TRUNCATE TABLE project_photos');
mysql_query('TRUNCATE TABLE t0101designprogress');
mysql_query('TRUNCATE TABLE t012issues');
mysql_query('TRUNCATE TABLE t013nonconformitynotice');
mysql_query('TRUNCATE TABLE t014majoritems');
mysql_query('TRUNCATE TABLE t023project_progress_graph');
mysql_query('TRUNCATE TABLE t027project_drawings');
mysql_query('TRUNCATE TABLE t027project_photos');
mysql_query('TRUNCATE TABLE t031project_albums');
mysql_query('TRUNCATE TABLE t031project_drawingalbums');
mysql_query('TRUNCATE TABLE t32project_videos');
mysql_query('TRUNCATE TABLE template_progress');
mysql_query('TRUNCATE TABLE users_log');
mysql_query('TRUNCATE TABLE yearly_holidays');
?>
